### ISSUE TITLE
how to use it in Windows10？

### ISSUE THREAD

**Issue by xepo12** [HenryzhaoH/sharepoint-batch-download-listgen#1]
how to use it in Windows10？
如何在win10 使用？

**Comment by HenryzhaoH** [comment]
I've updated the README. 
Please install python3 and download aria2 first, then follow the instructions in the README and from the program output.

我更新了说明文档，需要先安装一个 python3 运行环境，下载一下 aria2，之后运行脚本，根据提示操作即可。

**Comment by HenryzhaoH** [comment]
Feel free to comment here if there is any other problem.

如果有其他的问题，请继续回复这个issue。
